# Generated by Django 3.2.18 on 2023-02-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
