# Generated by Django 3.2.18 on 2023-02-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230219_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='EndDate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='StartDate',
            new_name='startDate',
        ),
    ]
